### ISSUE TITLE
 Permanently save images 

### ISSUE THREAD

**Issue by Mozzo1000** [AlfredoSequeida/venus#1]
Is there / can there be a way to save the images permanently to a selected directory instead of storing as temporary files? 
As a flag or configuration option. 

I have not tried and use your application yet so forgive me if this feature already exists.

**Comment by AlfredoSequeida** [comment]
@Mozzo1000 Currently there is not, but that is not a bad addition - I didn't think anyone might want to keep the images. This could be something to add after the rest of the program has been implemented.

**Comment by AlfredoSequeida** [comment]
@Mozzo1000 With the newest release (0.1.4). Images can now be stored in a directory set by the config file.
