### ISSUE TITLE
Cant find a config file

### ISSUE THREAD

**Issue by KrishnarajT** [AlfredoSequeida/venus#17]
I installed it with 
```sudo pip install venuspy```
but it didnt make the config file, so i made one, and now it says that it doesnt have any section headers.

Can I see a default config file as I couldnt find one!

**Comment by AlfredoSequeida** [comment]
Hey @KrishnarajT, the config file is automatically created on the first run. It should be in your home directory inside of a directory called `.config/venus`. The file is called `config`.

So for linux/unix like systems:
`/home/user_name/.config/venus/config`

And for a windows system:
`LocalDisk:\Users\user_name\.config\venus\config`

where the `user_name` coresponds to the account you installed venus with and `LocalDisk` is the installation partion on windows used by pip.
