### ISSUE TITLE
Consider outsourcing venus_demo.gif

### ISSUE THREAD

**Issue by aleksandar-todorovic** [AlfredoSequeida/venus#2]
The `.gif` alone is 16.9 MB in size. Outsourcing it to some other host would make the repository significantly smaller in size.

**Comment by AlfredoSequeida** [comment]
@aleksandar-todorovic I completely agree, this is something I noticed as well and will be changing soon.

**Comment by AlfredoSequeida** [comment]
@aleksandar-todorovic It seems that GitHub has an error with hosting files somewhere else. I got the file size down to about 6MB and tried hosting it on imgur, but I get a Content length exceeded error. So, for the time being, I decided to replace the 17MB file with the 6MB file instead.

**Comment by aleksandar-todorovic** [comment]
Almost a third of the size of its previous version? I think that's a reasonable size of it, so I'm gonna close this.
