### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by CaseyKnauss** [AlfredoSequeida/venus#3]
I did a little testing on windows 10. First thing I had to do was copy over the os_tools into the sitepackages directory after pip install. 

After running venus it successfully removed the background but didn't set a new one.  Hope that info helps working towards windows 10 usage.

**Comment by AlfredoSequeida** [comment]
Hi! Thank you, I am running into the same issue. But it is a strange bug that I need to do more research on. It seems that SystemParametersInfoW is having trouble finding the image if the file is generated by the get_wall() function, but not if it's generated by a string (which is the same string at the end anyways). Maybe it's the encoding of the string.

**Comment by AlfredoSequeida** [comment]
This issue has been fixed with the newest release.

**Comment by AlfredoSequeida** [comment]
The windows install has been fixed with the latest release 0.1.0
