### ISSUE TITLE
Verified working in Gentoo

### ISSUE THREAD

**Issue by geezuh** [AlfredoSequeida/venus#5]

**Comment by AlfredoSequeida** [comment]
Nice! I'll add that to the list of verified working operating systems. @geezuh, what version of Gentoo did you test it on?

**Comment by geezuh** [comment]
I’m new to gentoo, so I’m not sure... it appears to be versionless due to
its rolling release?

**Comment by AlfredoSequeida** [comment]
@geezuh try running 

uname -r

That should give you the release version. 

Also what's is the output of 

echo $DESKTOP_SESSION

**Comment by geezuh** [comment]
Linux trunks 4.19.72-gentoo #1 SMP Tue Oct 1 00:27:11 CDT 2019 x86_64
Intel(R) Core(TM) i3 CPU M 350 @ 2.27GHz GenuineIntel GNU/Linux
DESKTOP_SESSION isn't set, but I am running i3, and i put venus in my
.xinitrc

**Comment by geezuh** [comment]
sorry, uname -r is:
Linux trunks 4.19.72-gentoo #1 SMP Tue Oct 1 00:27:11 CDT 2019 x86_64
Intel(R) Core(TM) i3 CPU M 350 @ 2.27GHz GenuineIntel GNU/Linux

**Comment by AlfredoSequeida** [comment]
@geezuh, oh ok, so I'm guessing you are using feh to set the wallpaper, which explains why it works. Thank you!

**Comment by geezuh** [comment]
Yes, I do have feh installed.
